behaviors:
    ShootOnGoal:
        trainer_type: ppo
        summary_freq: 50000
        time_horizon: 64
        max_steps: 2000000        
        hyperparameters:
            beta: 0.005
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 3
            learning_rate: 0.0003
            batch_size: 32
            buffer_size: 40960
            learning_rate_schedule: linear    
        network_settings:
            hidden_units: 256
            num_layers: 2
            normalize: true
            conditioning_type: hyper
        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.995
                network_settings: 
                    normalize: true
                    hidden_units: 256
                
            